[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/tahashieenavaz/nonlinear"
Repository = "https://github.com/tahashieenavaz/nonlinear"
Documentation = "https://github.com/tahashieenavaz/nonlinear"

[project]
name = "nonlinear"
dynamic = ["version"] 
description = "A hand-curated collection of activation functions for deep learning research."
readme = "README.md"
requires-python = ">=3.8"
keywords = ["activation function", "deep learning", "machine learning", "non-linearity"]
authors = [
    { name = "Taha Shieenavaz", email = "tahashieenavaz@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = ["torch"]

[tool.setuptools_scm]