name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml

  build-and-publish:
    needs: run-tests
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build tools
        run: python -m pip install --upgrade build
      - name: Build the package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1